### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by prasadgopal**
Update go version to 1.13

### CODE REVIEW

**Comment by mariusae** [comment]
Have you looked into these failures?

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
985Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

**Comment by prasadgopal** [comment]
I don't know what that error is. But there is test failure. @swami-m 
I don't seem to have access to kick off another travis build.

 --- FAIL: TestWatcher (1.22s)
    watcher_test.go:131: got 2, want 3
    watcher_test.go:137: got 1, want 2
FAIL
FAIL	github.com/grailbio/reflow/ec2cluster/volume	1.496s

**Comment by swami-m** [comment]
> I don't know what that error is. But there is test failure. @swami-m
> I don't seem to have access to kick off another travis build.
> 
> --- FAIL: TestWatcher (1.22s)
> watcher_test.go:131: got 2, want 3
> watcher_test.go:137: got 1, want 2
> FAIL
> FAIL github.com/grailbio/reflow/ec2cluster/volume 1.496s

Hmm, I ran it multiple times with `go test -count 100` and also ran `go test -race` and it didn't fail.

**Comment by prasadgopal** [comment]
I can look into why this test in failing later. This change which update the infra package and the go version for travis is still useful.

**Pull request closed without merging**
